import { WeaponInfo, WeaponType } from '../types/physics';

export const WEAPON_REGISTRY: Record<WeaponType, WeaponInfo> = {
  physgun: {
    id: 'physgun',
    name: 'Pistola Gravitatoria (Physgun)',
    category: 'tool',
    damage: 0,
    fireRate: 50,
    ammo: Infinity,
    maxAmmo: Infinity,
    description: 'Agarra, levanta, congela y lanza cuerpos y objetos con física cuántica.',
    iconName: 'Magnet',
    color: '#06b6d4',
  },
  pistol: {
    id: 'pistol',
    name: 'Pistola 9mm Táctica',
    category: 'firearm',
    damage: 28,
    fireRate: 200,
    ammo: 15,
    maxAmmo: 15,
    description: 'Pistola semiautomática de alta precisión y daño moderado.',
    iconName: 'Crosshair',
    color: '#64748b',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Escopeta Calibre 12',
    category: 'firearm',
    damage: 18, // per pellet (8 pellets = ~144)
    fireRate: 850,
    ammo: 8,
    maxAmmo: 8,
    description: 'Dispersión letal de 8 perdigones capaz de desmembrar extremidades a corta distancia.',
    iconName: 'Zap',
    color: '#ea580c',
  },
  ak47: {
    id: 'ak47',
    name: 'Rifle de Asalto AK-47',
    category: 'firearm',
    damage: 34,
    fireRate: 110,
    ammo: 30,
    maxAmmo: 30,
    description: 'Fuego automático rápido de alto calibre 7.62 con penetración de armaduras.',
    iconName: 'Flame',
    color: '#ca8a04',
  },
  sniper: {
    id: 'sniper',
    name: 'Rifle Francotirador .50',
    category: 'firearm',
    damage: 120,
    fireRate: 1100,
    ammo: 5,
    maxAmmo: 5,
    description: 'Proyectil devastador de alta velocidad que atraviesa múltiples cuerpos y rompe huesos.',
    iconName: 'Target',
    color: '#84cc16',
  },
  rpg: {
    id: 'rpg',
    name: 'Lanzacohetes RPG-7',
    category: 'explosive',
    damage: 250,
    fireRate: 1800,
    ammo: 3,
    maxAmmo: 3,
    description: 'Cohete explosivo propulsado que desintegra y arroja cuerpos por los aires.',
    iconName: 'Rocket',
    color: '#dc2626',
  },
  katana: {
    id: 'katana',
    name: 'Katana Afilada',
    category: 'melee',
    damage: 90,
    fireRate: 350,
    ammo: Infinity,
    maxAmmo: Infinity,
    description: 'Corte de alta velocidad que cercena articulaciones y provoca hemorragias.',
    iconName: 'Sword',
    color: '#e2e8f0',
  },
  sledgehammer: {
    id: 'sledgehammer',
    name: 'Mazo de Demolición Pesado',
    category: 'melee',
    damage: 110,
    fireRate: 600,
    ammo: Infinity,
    maxAmmo: Infinity,
    description: 'Impacto contundente capaz de fracturar huesos instantáneamente.',
    iconName: 'Hammer',
    color: '#78716c',
  },
  grenade: {
    id: 'grenade',
    name: 'Granada de Fragmentación',
    category: 'explosive',
    damage: 180,
    fireRate: 1000,
    ammo: 6,
    maxAmmo: 6,
    description: 'Granada arrojadiza con temporizador de 2.5s y metralla.',
    iconName: 'Bomb',
    color: '#16a34a',
  },
  c4: {
    id: 'c4',
    name: 'Carga C4 con Detonador',
    category: 'explosive',
    damage: 320,
    fireRate: 800,
    ammo: 4,
    maxAmmo: 4,
    description: 'Explosivo plástico adherente activado a distancia.',
    iconName: 'Radio',
    color: '#f97316',
  },
  syringe_adrenaline: {
    id: 'syringe_adrenaline',
    name: 'Jeringa de Adrenalina (Revivir)',
    category: 'syringe',
    damage: -100, // Heals
    fireRate: 500,
    ammo: 10,
    maxAmmo: 10,
    description: 'Restaura la vida, para las hemorragias, repara huesos rotos y revive al ragdoll.',
    iconName: 'Activity',
    color: '#22c55e',
  },
  syringe_acid: {
    id: 'syringe_acid',
    name: 'Jeringa de Ácido Corrosivo',
    category: 'syringe',
    damage: 60,
    fireRate: 500,
    ammo: 10,
    maxAmmo: 10,
    description: 'Disuelve los tejidos y la piel dejando ver los huesos y debilita la estructura.',
    iconName: 'Skull',
    color: '#a855f7',
  },
  syringe_nitro: {
    id: 'syringe_nitro',
    name: 'Jeringa de Nitroglicerina',
    category: 'syringe',
    damage: 0,
    fireRate: 500,
    ammo: 10,
    maxAmmo: 10,
    description: 'Hace que el cuerpo explote ante cualquier golpe o impacto fuerte.',
    iconName: 'Sparkles',
    color: '#ef4444',
  },
  syringe_antigrav: {
    id: 'syringe_antigrav',
    name: 'Jeringa Anti-Gravedad',
    category: 'syringe',
    damage: 0,
    fireRate: 500,
    ammo: 10,
    maxAmmo: 10,
    description: 'Otorga gravedad negativa (-g) al cuerpo para que flote en el aire.',
    iconName: 'Feather',
    color: '#38bdf8',
  },
};
